policy:
  - template: ["bug_report.yml"]
    section:
      - id: [flow_name]
        block-list: [other]
        label:
          - name: auto adb
            keys: ["Auto ADB Mode", "Auto ADB + Shizuku"]
          - name: islamic prayer alarm
            keys: ["Islamic Prayer Alarm"]
          - name: private dns
            keys: ["Toggle Private DNS", "Private DNS Changer", "Private DNS+"]
          - name: quickie
            keys: ["Quickie"]
