blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/rahaaatul/automate-flows/discussions/new?category=ideas
    about: Ask for feature request or share your ideas here.
  - name: Discuss
    url: https://github.com/rahaaatul/automate-flows/discussions/new?category=general
    about: Discuss your thoughts/opinions on my flows here.
